version: '3.8'

services:
  db:
    image: postgres:15
    container_name: forum_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forum_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  forum-api:
    build: .
    container_name: forum_api
    depends_on:
      - db
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forum_db
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
